package config

// Defaults — единственные значения по умолчанию (раздел 13 ТЗ).
// В остальном коде дублировать эти числа запрещено (строгое правило 2).
func Defaults() *Config {
	return &Config{
		Coordinator: Coordinator{
			Bind: "127.0.0.1",
			// Петля, частные сети и Tailscale CGNAT (раздел 13).
			AllowCIDRs: []string{
				"127.0.0.0/8",
				"10.0.0.0/8",
				"172.16.0.0/12",
				"192.168.0.0/16",
				"100.64.0.0/10",
			},
			GatewayPort:      8787,
			APIPort:          8788,
			GatewayURL:       "http://127.0.0.1:8787",
			TokenEnv:         "RUNPILOT_TOKEN",
			DBPath:           "~/.local/share/runpilot/runpilot.db",
			ShutdownGraceSec: 30,
			// v2 (раздел 2.3): повтор привязки + встроенный узел.
			BindRetrySec: 5,
			BindAlertMin: 10,
			HeartbeatSec: 5,
			DistDir:      "~/.local/share/runpilot/dist",
			EmbeddedNode: true,
		},
		Scheduler: Scheduler{
			TickMS:             500,
			AgingSec:           900,
			PreferWaitSec:      300,
			PinUnavailableSec:  120,
			AffinityTTLSec:     900,
			ResumeBackoffSec:   30,
			AutoRequeueMax:     3,
			SnapshotMaxAgeSec:  5,
			DispatchStableSec:  3,
			ExternalConfirmSec: 3,
			CooldownSec:        2,
			RecoveryWindowSec:  15,
		},
		Dispatch: Dispatch{
			NodeReplyTimeoutSec: 5,
			StartConfirmSec:     20,
			ResumeKeyDelayMS:    150,
			BudgetP95MS:         1500,
		},
		Turn: Turn{
			DoneQuietSec:         5,
			DoneStableSec:        5,
			ToolHoldMaxSec:       900,
			ApprovalHoldMaxSec:   600,
			UnknownMaxSec:        60,
			NodeLostReleaseSec:   120,
			AutoEnqueueStableSec: 20,
			KillGraceSec:         10,
		},
		Gateway: Gateway{
			HoldMaxSec:    60,
			MaxBodyMB:     32,
			RetryAfterSec: 30,
			MaxInflight:   256,
		},
		Monitor: Monitor{
			HealthIntervalSec:  5,
			HealthTimeoutSec:   3,
			HealthDownAfter:    3,
			HealthUpAfter:      2,
			MetricsIntervalSec: 2,
			MetricsTimeoutSec:  2,
			RateWindowSec:      10,
			HistoryWindowMin:   10,
			ModelsRefreshSec:   60,
			DiskFreeMinMB:      1024,
			DiskCheckSec:       300,
			SafeProbeSec:       10,
		},
		Limits: Limits{
			MaxSessionsPerNode:   32,
			MaxQueueLength:       256,
			MaxPaneSnapshotBytes: 131072,
			TokenMinLen:          16,
		},
		Web: Web{
			Bind:            "127.0.0.1",
			Port:            8790,
			PublicURL:       "http://127.0.0.1:8790",
			SessionTTLDays:  14,
			LoginRatePerMin: 10,
			ScreenIntervalMS:      2000,
			PasteVerifySec:        10,
			PasteMaxKB:            64,
			SpawnReadySec:         5,
			DirsMax:               100,
			SSEReplay:             200,
			SSEClientsMax:         20,
			ScreensPerClientMax:   10,
			TerminalsPerNodeMax:   5,
			TerminalIdleMin:       30,
			UndoSec:               10,
			PageSize:              50,
			IdempotencyTTLSec:     300,
			ProbeTimeoutSec:       5,
			NodeOpTimeoutSec:      5,
			UpdateTimeoutSec:      15,
		},
		Servers: nil,
		Profiles: Profiles{
			Qwen: ProfileQwen{
				ModelAlias: "qwen3.6-27b",
			},
		},
		Notify: Notify{
			Telegram: Telegram{
				BotTokenEnv: "RUNPILOT_TG_TOKEN",
				ChatIDs:     nil,
				MinTurnSec:  60,
				CoalesceSec: 10,
				Kinds: []string{
					"server_fault", "oom", "emergency", "bind_alert",
					"db_error", "external_process", "node_update",
				},
			},
			Alerts: Alerts{
				QueueWaitMin:    10,
				WaitUISec:       300,
				PromptRemindMin: 15,
			},
		},
		Retention: Retention{
			RequestsDays:      30,
			EventsDays:        30,
			GoneSessionsDays:  7,
			AuditDays:         90,
			NotificationsDays: 30,
			ExternalDays:      7,
		},
		Client: Client{
			Coordinator: "http://127.0.0.1:8788",
			TokenEnv:    "RUNPILOT_TOKEN",
		},
		Node: Node{
			Host:            "",
			TmuxSockets:     []string{"default"},
			ScanIntervalSec: 2,
			GPU:             "none",
			GPUServer:       "",
			OfflineAfterSec:     30,
			HealthIntervalSec:   15,
			ProjectRootsDefault: []string{"~"},
		},
		Faults: Faults{
			WindowSec:       300,
			QuarantineCount: 3,
			QuarantineSec:   300,
			FlapCount:       5,
			FlapWindowSec:   600,
		},
		Enroll: Enroll{
			TokenTTLMin:        60,
			UpdateRetryMin:     5,
			SelftestTimeoutSec: 30,
		},
		External: External{
			Detect:       true,
			KillGraceSec: 5,
		},
		Jobs: Jobs{
			HeartbeatSec:        15,
			HeartbeatTimeoutSec: 45,
			WaitMaxDefaultSec:   3600,
			Slots:               4,
		},
		Backup: Backup{
			DailyAtUTC: "03:00",
			Keep:       7,
		},
	}
}
